INSERT INTO Municipality VALUES ('Aberdeen township', 'Monmouth');
INSERT INTO Municipality VALUES ('Absecon city', 'Atlantic');
INSERT INTO Municipality VALUES ('Alexandria township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Allamuchy township', 'Warren');
INSERT INTO Municipality VALUES ('Allendale borough', 'Bergen');
INSERT INTO Municipality VALUES ('Allenhurst borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Allentown borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Alloway township', 'Salem');
INSERT INTO Municipality VALUES ('Alpha borough', 'Warren');
INSERT INTO Municipality VALUES ('Alpine borough', 'Bergen');
INSERT INTO Municipality VALUES ('Andover borough', 'Sussex');
INSERT INTO Municipality VALUES ('Andover township', 'Sussex');
INSERT INTO Municipality VALUES ('Asbury Park city', 'Monmouth');
INSERT INTO Municipality VALUES ('Atlantic City city', 'Atlantic');
INSERT INTO Municipality VALUES ('Atlantic Highlands borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Audubon borough', 'Camden');
INSERT INTO Municipality VALUES ('Audubon Park borough', 'Camden');
INSERT INTO Municipality VALUES ('Avalon borough', 'Cape May');
INSERT INTO Municipality VALUES ('Avon-by-the-Sea borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Barnegat Light borough', 'Ocean');
INSERT INTO Municipality VALUES ('Barnegat township', 'Ocean');
INSERT INTO Municipality VALUES ('Barrington borough', 'Camden');
INSERT INTO Municipality VALUES ('Bass River township', 'Burlington');
INSERT INTO Municipality VALUES ('Bay Head borough', 'Ocean');
INSERT INTO Municipality VALUES ('Bayonne city', 'Hudson');
INSERT INTO Municipality VALUES ('Beach Haven borough', 'Ocean');
INSERT INTO Municipality VALUES ('Beachwood borough', 'Ocean');
INSERT INTO Municipality VALUES ('Bedminster township', 'Somerset');
INSERT INTO Municipality VALUES ('Belleville township', 'Essex');
INSERT INTO Municipality VALUES ('Bellmawr borough', 'Camden');
INSERT INTO Municipality VALUES ('Belmar borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Belvidere town', 'Warren');
INSERT INTO Municipality VALUES ('Bergenfield borough', 'Bergen');
INSERT INTO Municipality VALUES ('Berkeley Heights township', 'Union');
INSERT INTO Municipality VALUES ('Berkeley township', 'Ocean');
INSERT INTO Municipality VALUES ('Berlin borough', 'Camden');
INSERT INTO Municipality VALUES ('Berlin township', 'Camden');
INSERT INTO Municipality VALUES ('Bernards township', 'Somerset');
INSERT INTO Municipality VALUES ('Bernardsville borough', 'Somerset');
INSERT INTO Municipality VALUES ('Bethlehem township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Beverly city', 'Burlington');
INSERT INTO Municipality VALUES ('Blairstown township', 'Warren');
INSERT INTO Municipality VALUES ('Bloomfield township', 'Essex');
INSERT INTO Municipality VALUES ('Bloomingdale borough', 'Passaic');
INSERT INTO Municipality VALUES ('Bloomsbury borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Bogota borough', 'Bergen');
INSERT INTO Municipality VALUES ('Boonton town', 'Morris');
INSERT INTO Municipality VALUES ('Boonton township', 'Morris');
INSERT INTO Municipality VALUES ('Bordentown city', 'Burlington');
INSERT INTO Municipality VALUES ('Bordentown township', 'Burlington');
INSERT INTO Municipality VALUES ('Bound Brook borough', 'Somerset');
INSERT INTO Municipality VALUES ('Bradley Beach borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Branchburg township', 'Somerset');
INSERT INTO Municipality VALUES ('Branchville borough', 'Sussex');
INSERT INTO Municipality VALUES ('Brick township', 'Ocean');
INSERT INTO Municipality VALUES ('Bridgeton city', 'Cumberland');
INSERT INTO Municipality VALUES ('Bridgewater township', 'Somerset');
INSERT INTO Municipality VALUES ('Brielle borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Brigantine city', 'Atlantic');
INSERT INTO Municipality VALUES ('Brooklawn borough', 'Camden');
INSERT INTO Municipality VALUES ('Buena borough', 'Atlantic');
INSERT INTO Municipality VALUES ('Buena Vista township', 'Atlantic');
INSERT INTO Municipality VALUES ('Burlington city', 'Burlington');
INSERT INTO Municipality VALUES ('Burlington township', 'Burlington');
INSERT INTO Municipality VALUES ('Butler borough', 'Morris');
INSERT INTO Municipality VALUES ('Byram township', 'Sussex');
INSERT INTO Municipality VALUES ('Caldwell borough', 'Essex');
INSERT INTO Municipality VALUES ('Califon borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Camden city', 'Camden');
INSERT INTO Municipality VALUES ('Cape May city', 'Cape May');
INSERT INTO Municipality VALUES ('Cape May Point borough', 'Cape May');
INSERT INTO Municipality VALUES ('Carlstadt borough', 'Bergen');
INSERT INTO Municipality VALUES ('Carneys Point township', 'Salem');
INSERT INTO Municipality VALUES ('Carteret borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Cedar Grove township', 'Essex');
INSERT INTO Municipality VALUES ('Chatham borough', 'Morris');
INSERT INTO Municipality VALUES ('Chatham township', 'Morris');
INSERT INTO Municipality VALUES ('Cherry Hill township', 'Camden');
INSERT INTO Municipality VALUES ('Chesilhurst borough', 'Camden');
INSERT INTO Municipality VALUES ('Chester borough', 'Morris');
INSERT INTO Municipality VALUES ('Chester township', 'Morris');
INSERT INTO Municipality VALUES ('Chesterfield township', 'Burlington');
INSERT INTO Municipality VALUES ('Cinnaminson township', 'Burlington');
INSERT INTO Municipality VALUES ('City of Orange township', 'Essex');
INSERT INTO Municipality VALUES ('Clark township', 'Union');
INSERT INTO Municipality VALUES ('Clayton borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Clementon borough', 'Camden');
INSERT INTO Municipality VALUES ('Cliffside Park borough', 'Bergen');
INSERT INTO Municipality VALUES ('Clifton city', 'Passaic');
INSERT INTO Municipality VALUES ('Clinton town', 'Hunterdon');
INSERT INTO Municipality VALUES ('Clinton township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Closter borough', 'Bergen');
INSERT INTO Municipality VALUES ('Collingswood borough', 'Camden');
INSERT INTO Municipality VALUES ('Colts Neck township', 'Monmouth');
INSERT INTO Municipality VALUES ('Commercial township', 'Cumberland');
INSERT INTO Municipality VALUES ('Corbin City city', 'Atlantic');
INSERT INTO Municipality VALUES ('Cranbury township', 'Middlesex');
INSERT INTO Municipality VALUES ('Cranford township', 'Union');
INSERT INTO Municipality VALUES ('Cresskill borough', 'Bergen');
INSERT INTO Municipality VALUES ('Deal borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Deerfield township', 'Cumberland');
INSERT INTO Municipality VALUES ('Delanco township', 'Burlington');
INSERT INTO Municipality VALUES ('Delaware township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Delran township', 'Burlington');
INSERT INTO Municipality VALUES ('Demarest borough', 'Bergen');
INSERT INTO Municipality VALUES ('Dennis township', 'Cape May');
INSERT INTO Municipality VALUES ('Denville township', 'Morris');
INSERT INTO Municipality VALUES ('Deptford township', 'Gloucester');
INSERT INTO Municipality VALUES ('Dover town', 'Morris');
INSERT INTO Municipality VALUES ('Downe township', 'Cumberland');
INSERT INTO Municipality VALUES ('Dumont borough', 'Bergen');
INSERT INTO Municipality VALUES ('Dunellen borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Eagleswood township', 'Ocean');
INSERT INTO Municipality VALUES ('East Amwell township', 'Hunterdon');
INSERT INTO Municipality VALUES ('East Brunswick township', 'Middlesex');
INSERT INTO Municipality VALUES ('East Greenwich township', 'Gloucester');
INSERT INTO Municipality VALUES ('East Hanover township', 'Morris');
INSERT INTO Municipality VALUES ('East Newark borough', 'Hudson');
INSERT INTO Municipality VALUES ('East Orange city', 'Essex');
INSERT INTO Municipality VALUES ('East Rutherford borough', 'Bergen');
INSERT INTO Municipality VALUES ('East Windsor township', 'Mercer');
INSERT INTO Municipality VALUES ('Eastampton township', 'Burlington');
INSERT INTO Municipality VALUES ('Eatontown borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Edgewater borough', 'Bergen');
INSERT INTO Municipality VALUES ('Edgewater Park township', 'Burlington');
INSERT INTO Municipality VALUES ('Edison township', 'Middlesex');
INSERT INTO Municipality VALUES ('Egg Harbor City city', 'Atlantic');
INSERT INTO Municipality VALUES ('Egg Harbor township', 'Atlantic');
INSERT INTO Municipality VALUES ('Elizabeth city', 'Union');
INSERT INTO Municipality VALUES ('Elk township', 'Gloucester');
INSERT INTO Municipality VALUES ('Elmer borough', 'Salem');
INSERT INTO Municipality VALUES ('Elmwood Park borough', 'Bergen');
INSERT INTO Municipality VALUES ('Elsinboro township', 'Salem');
INSERT INTO Municipality VALUES ('Emerson borough', 'Bergen');
INSERT INTO Municipality VALUES ('Englewood city', 'Bergen');
INSERT INTO Municipality VALUES ('Englewood Cliffs borough', 'Bergen');
INSERT INTO Municipality VALUES ('Englishtown borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Essex Fells borough', 'Essex');
INSERT INTO Municipality VALUES ('Estell Manor city', 'Atlantic');
INSERT INTO Municipality VALUES ('Evesham township', 'Burlington');
INSERT INTO Municipality VALUES ('Ewing township', 'Mercer');
INSERT INTO Municipality VALUES ('Fair Haven borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Fair Lawn borough', 'Bergen');
INSERT INTO Municipality VALUES ('Fairfield township', 'Cumberland');
INSERT INTO Municipality VALUES ('Fairfield township', 'Essex');
INSERT INTO Municipality VALUES ('Fairview borough', 'Bergen');
INSERT INTO Municipality VALUES ('Fanwood borough', 'Union');
INSERT INTO Municipality VALUES ('Far Hills borough', 'Somerset');
INSERT INTO Municipality VALUES ('Farmingdale borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Fieldsboro borough', 'Burlington');
INSERT INTO Municipality VALUES ('Flemington borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Florence township', 'Burlington');
INSERT INTO Municipality VALUES ('Florham Park borough', 'Morris');
INSERT INTO Municipality VALUES ('Folsom borough', 'Atlantic');
INSERT INTO Municipality VALUES ('Fort Lee borough', 'Bergen');
INSERT INTO Municipality VALUES ('Frankford township', 'Sussex');
INSERT INTO Municipality VALUES ('Franklin borough', 'Sussex');
INSERT INTO Municipality VALUES ('Franklin Lakes borough', 'Bergen');
INSERT INTO Municipality VALUES ('Franklin township', 'Gloucester');
INSERT INTO Municipality VALUES ('Franklin township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Franklin township', 'Somerset');
INSERT INTO Municipality VALUES ('Franklin township', 'Warren');
INSERT INTO Municipality VALUES ('Fredon township', 'Sussex');
INSERT INTO Municipality VALUES ('Freehold borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Freehold township', 'Monmouth');
INSERT INTO Municipality VALUES ('Frelinghuysen township', 'Warren');
INSERT INTO Municipality VALUES ('Frenchtown borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Galloway township', 'Atlantic');
INSERT INTO Municipality VALUES ('Garfield city', 'Bergen');
INSERT INTO Municipality VALUES ('Garwood borough', 'Union');
INSERT INTO Municipality VALUES ('Gibbsboro borough', 'Camden');
INSERT INTO Municipality VALUES ('Glassboro borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Glen Gardner borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Glen Ridge borough', 'Essex');
INSERT INTO Municipality VALUES ('Glen Rock borough', 'Bergen');
INSERT INTO Municipality VALUES ('Gloucester City city', 'Camden');
INSERT INTO Municipality VALUES ('Gloucester township', 'Camden');
INSERT INTO Municipality VALUES ('Green Brook township', 'Somerset');
INSERT INTO Municipality VALUES ('Green township', 'Sussex');
INSERT INTO Municipality VALUES ('Greenwich township', 'Cumberland');
INSERT INTO Municipality VALUES ('Greenwich township', 'Gloucester');
INSERT INTO Municipality VALUES ('Greenwich township', 'Warren');
INSERT INTO Municipality VALUES ('Guttenberg town', 'Hudson');
INSERT INTO Municipality VALUES ('Hackensack city', 'Bergen');
INSERT INTO Municipality VALUES ('Hackettstown town', 'Warren');
INSERT INTO Municipality VALUES ('Haddon Heights borough', 'Camden');
INSERT INTO Municipality VALUES ('Haddon township', 'Camden');
INSERT INTO Municipality VALUES ('Haddonfield borough', 'Camden');
INSERT INTO Municipality VALUES ('Hainesport township', 'Burlington');
INSERT INTO Municipality VALUES ('Haledon borough', 'Passaic');
INSERT INTO Municipality VALUES ('Hamburg borough', 'Sussex');
INSERT INTO Municipality VALUES ('Hamilton township', 'Atlantic');
INSERT INTO Municipality VALUES ('Hamilton township', 'Mercer');
INSERT INTO Municipality VALUES ('Hammonton town', 'Atlantic');
INSERT INTO Municipality VALUES ('Hampton borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Hampton township', 'Sussex');
INSERT INTO Municipality VALUES ('Hanover township', 'Morris');
INSERT INTO Municipality VALUES ('Harding township', 'Morris');
INSERT INTO Municipality VALUES ('Hardwick township', 'Warren');
INSERT INTO Municipality VALUES ('Hardyston township', 'Sussex');
INSERT INTO Municipality VALUES ('Harmony township', 'Warren');
INSERT INTO Municipality VALUES ('Harrington Park borough', 'Bergen');
INSERT INTO Municipality VALUES ('Harrison town', 'Hudson');
INSERT INTO Municipality VALUES ('Harrison township', 'Gloucester');
INSERT INTO Municipality VALUES ('Harvey Cedars borough', 'Ocean');
INSERT INTO Municipality VALUES ('Hasbrouck Heights borough', 'Bergen');
INSERT INTO Municipality VALUES ('Haworth borough', 'Bergen');
INSERT INTO Municipality VALUES ('Hawthorne borough', 'Passaic');
INSERT INTO Municipality VALUES ('Hazlet township', 'Monmouth');
INSERT INTO Municipality VALUES ('Helmetta borough', 'Middlesex');
INSERT INTO Municipality VALUES ('High Bridge borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Highland Park borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Highlands borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Hightstown borough', 'Mercer');
INSERT INTO Municipality VALUES ('Hillsborough township', 'Somerset');
INSERT INTO Municipality VALUES ('Hillsdale borough', 'Bergen');
INSERT INTO Municipality VALUES ('Hillside township', 'Union');
INSERT INTO Municipality VALUES ('Hi-Nella borough', 'Camden');
INSERT INTO Municipality VALUES ('Hoboken city', 'Hudson');
INSERT INTO Municipality VALUES ('Ho-Ho-Kus borough', 'Bergen');
INSERT INTO Municipality VALUES ('Holland township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Holmdel township', 'Monmouth');
INSERT INTO Municipality VALUES ('Hopatcong borough', 'Sussex');
INSERT INTO Municipality VALUES ('Hope township', 'Warren');
INSERT INTO Municipality VALUES ('Hopewell borough', 'Mercer');
INSERT INTO Municipality VALUES ('Hopewell township', 'Cumberland');
INSERT INTO Municipality VALUES ('Hopewell township', 'Mercer');
INSERT INTO Municipality VALUES ('Howell township', 'Monmouth');
INSERT INTO Municipality VALUES ('Independence township', 'Warren');
INSERT INTO Municipality VALUES ('Interlaken borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Irvington township', 'Essex');
INSERT INTO Municipality VALUES ('Island Heights borough', 'Ocean');
INSERT INTO Municipality VALUES ('Jackson township', 'Ocean');
INSERT INTO Municipality VALUES ('Jamesburg borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Jefferson township', 'Morris');
INSERT INTO Municipality VALUES ('Jersey City city', 'Hudson');
INSERT INTO Municipality VALUES ('Keansburg borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Kearny town', 'Hudson');
INSERT INTO Municipality VALUES ('Kenilworth borough', 'Union');
INSERT INTO Municipality VALUES ('Keyport borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Kingwood township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Kinnelon borough', 'Morris');
INSERT INTO Municipality VALUES ('Knowlton township', 'Warren');
INSERT INTO Municipality VALUES ('Lacey township', 'Ocean');
INSERT INTO Municipality VALUES ('Lafayette township', 'Sussex');
INSERT INTO Municipality VALUES ('Lake Como borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Lakehurst borough', 'Ocean');
INSERT INTO Municipality VALUES ('Lakewood township', 'Ocean');
INSERT INTO Municipality VALUES ('Lambertville city', 'Hunterdon');
INSERT INTO Municipality VALUES ('Laurel Springs borough', 'Camden');
INSERT INTO Municipality VALUES ('Lavallette borough', 'Ocean');
INSERT INTO Municipality VALUES ('Lawnside borough', 'Camden');
INSERT INTO Municipality VALUES ('Lawrence township', 'Cumberland');
INSERT INTO Municipality VALUES ('Lawrence township', 'Mercer');
INSERT INTO Municipality VALUES ('Lebanon borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Lebanon township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Leonia borough', 'Bergen');
INSERT INTO Municipality VALUES ('Liberty township', 'Warren');
INSERT INTO Municipality VALUES ('Lincoln Park borough', 'Morris');
INSERT INTO Municipality VALUES ('Linden city', 'Union');
INSERT INTO Municipality VALUES ('Lindenwold borough', 'Camden');
INSERT INTO Municipality VALUES ('Linwood city', 'Atlantic');
INSERT INTO Municipality VALUES ('Little Egg Harbor township', 'Ocean');
INSERT INTO Municipality VALUES ('Little Falls township', 'Passaic');
INSERT INTO Municipality VALUES ('Little Ferry borough', 'Bergen');
INSERT INTO Municipality VALUES ('Little Silver borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Livingston township', 'Essex');
INSERT INTO Municipality VALUES ('Loch Arbour village', 'Monmouth');
INSERT INTO Municipality VALUES ('Lodi borough', 'Bergen');
INSERT INTO Municipality VALUES ('Logan township', 'Gloucester');
INSERT INTO Municipality VALUES ('Long Beach township', 'Ocean');
INSERT INTO Municipality VALUES ('Long Branch city', 'Monmouth');
INSERT INTO Municipality VALUES ('Long Hill township', 'Morris');
INSERT INTO Municipality VALUES ('Longport borough', 'Atlantic');
INSERT INTO Municipality VALUES ('Lopatcong township', 'Warren');
INSERT INTO Municipality VALUES ('Lower Alloways Creek township', 'Salem');
INSERT INTO Municipality VALUES ('Lower township', 'Cape May');
INSERT INTO Municipality VALUES ('Lumberton township', 'Burlington');
INSERT INTO Municipality VALUES ('Lyndhurst township', 'Bergen');
INSERT INTO Municipality VALUES ('Madison borough', 'Morris');
INSERT INTO Municipality VALUES ('Magnolia borough', 'Camden');
INSERT INTO Municipality VALUES ('Mahwah township', 'Bergen');
INSERT INTO Municipality VALUES ('Manalapan township', 'Monmouth');
INSERT INTO Municipality VALUES ('Manasquan borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Manchester township', 'Ocean');
INSERT INTO Municipality VALUES ('Mannington township', 'Salem');
INSERT INTO Municipality VALUES ('Mansfield township', 'Burlington');
INSERT INTO Municipality VALUES ('Mansfield township', 'Warren');
INSERT INTO Municipality VALUES ('Mantoloking borough', 'Ocean');
INSERT INTO Municipality VALUES ('Mantua township', 'Gloucester');
INSERT INTO Municipality VALUES ('Manville borough', 'Somerset');
INSERT INTO Municipality VALUES ('Maple Shade township', 'Burlington');
INSERT INTO Municipality VALUES ('Maplewood township', 'Essex');
INSERT INTO Municipality VALUES ('Margate City city', 'Atlantic');
INSERT INTO Municipality VALUES ('Marlboro township', 'Monmouth');
INSERT INTO Municipality VALUES ('Matawan borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Maurice River township', 'Cumberland');
INSERT INTO Municipality VALUES ('Maywood borough', 'Bergen');
INSERT INTO Municipality VALUES ('Medford Lakes borough', 'Burlington');
INSERT INTO Municipality VALUES ('Medford township', 'Burlington');
INSERT INTO Municipality VALUES ('Mendham borough', 'Morris');
INSERT INTO Municipality VALUES ('Mendham township', 'Morris');
INSERT INTO Municipality VALUES ('Merchantville borough', 'Camden');
INSERT INTO Municipality VALUES ('Metuchen borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Middle township', 'Cape May');
INSERT INTO Municipality VALUES ('Middlesex borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Middletown township', 'Monmouth');
INSERT INTO Municipality VALUES ('Midland Park borough', 'Bergen');
INSERT INTO Municipality VALUES ('Milford borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Millburn township', 'Essex');
INSERT INTO Municipality VALUES ('Millstone borough', 'Somerset');
INSERT INTO Municipality VALUES ('Millstone township', 'Monmouth');
INSERT INTO Municipality VALUES ('Milltown borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Millville city', 'Cumberland');
INSERT INTO Municipality VALUES ('Mine Hill township', 'Morris');
INSERT INTO Municipality VALUES ('Monmouth Beach borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Monroe township', 'Gloucester');
INSERT INTO Municipality VALUES ('Monroe township', 'Middlesex');
INSERT INTO Municipality VALUES ('Montague township', 'Sussex');
INSERT INTO Municipality VALUES ('Montclair township', 'Essex');
INSERT INTO Municipality VALUES ('Montgomery township', 'Somerset');
INSERT INTO Municipality VALUES ('Montvale borough', 'Bergen');
INSERT INTO Municipality VALUES ('Montville township', 'Morris');
INSERT INTO Municipality VALUES ('Moonachie borough', 'Bergen');
INSERT INTO Municipality VALUES ('Moorestown township', 'Burlington');
INSERT INTO Municipality VALUES ('Morris Plains borough', 'Morris');
INSERT INTO Municipality VALUES ('Morris township', 'Morris');
INSERT INTO Municipality VALUES ('Morristown town', 'Morris');
INSERT INTO Municipality VALUES ('Mount Arlington borough', 'Morris');
INSERT INTO Municipality VALUES ('Mount Ephraim borough', 'Camden');
INSERT INTO Municipality VALUES ('Mount Holly township', 'Burlington');
INSERT INTO Municipality VALUES ('Mount Laurel township', 'Burlington');
INSERT INTO Municipality VALUES ('Mount Olive township', 'Morris');
INSERT INTO Municipality VALUES ('Mountain Lakes borough', 'Morris');
INSERT INTO Municipality VALUES ('Mountainside borough', 'Union');
INSERT INTO Municipality VALUES ('Mullica township', 'Atlantic');
INSERT INTO Municipality VALUES ('National Park borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Neptune City borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Neptune township', 'Monmouth');
INSERT INTO Municipality VALUES ('Netcong borough', 'Morris');
INSERT INTO Municipality VALUES ('New Brunswick city', 'Middlesex');
INSERT INTO Municipality VALUES ('New Hanover township', 'Burlington');
INSERT INTO Municipality VALUES ('New Milford borough', 'Bergen');
INSERT INTO Municipality VALUES ('New Providence borough', 'Union');
INSERT INTO Municipality VALUES ('Newark city', 'Essex');
INSERT INTO Municipality VALUES ('Newfield borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Newton town', 'Sussex');
INSERT INTO Municipality VALUES ('North Arlington borough', 'Bergen');
INSERT INTO Municipality VALUES ('North Bergen township', 'Hudson');
INSERT INTO Municipality VALUES ('North Brunswick township', 'Middlesex');
INSERT INTO Municipality VALUES ('North Caldwell borough', 'Essex');
INSERT INTO Municipality VALUES ('North Haledon borough', 'Passaic');
INSERT INTO Municipality VALUES ('North Hanover township', 'Burlington');
INSERT INTO Municipality VALUES ('North Plainfield borough', 'Somerset');
INSERT INTO Municipality VALUES ('North Wildwood city', 'Cape May');
INSERT INTO Municipality VALUES ('Northfield city', 'Atlantic');
INSERT INTO Municipality VALUES ('Northvale borough', 'Bergen');
INSERT INTO Municipality VALUES ('Norwood borough', 'Bergen');
INSERT INTO Municipality VALUES ('Nutley township', 'Essex');
INSERT INTO Municipality VALUES ('Oakland borough', 'Bergen');
INSERT INTO Municipality VALUES ('Oaklyn borough', 'Camden');
INSERT INTO Municipality VALUES ('Ocean City city', 'Cape May');
INSERT INTO Municipality VALUES ('Ocean Gate borough', 'Ocean');
INSERT INTO Municipality VALUES ('Ocean township', 'Monmouth');
INSERT INTO Municipality VALUES ('Ocean township', 'Ocean');
INSERT INTO Municipality VALUES ('Oceanport borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Ogdensburg borough', 'Sussex');
INSERT INTO Municipality VALUES ('Old Bridge township', 'Middlesex');
INSERT INTO Municipality VALUES ('Old Tappan borough', 'Bergen');
INSERT INTO Municipality VALUES ('Oldmans township', 'Salem');
INSERT INTO Municipality VALUES ('Oradell borough', 'Bergen');
INSERT INTO Municipality VALUES ('Oxford township', 'Warren');
INSERT INTO Municipality VALUES ('Palisades Park borough', 'Bergen');
INSERT INTO Municipality VALUES ('Palmyra borough', 'Burlington');
INSERT INTO Municipality VALUES ('Paramus borough', 'Bergen');
INSERT INTO Municipality VALUES ('Park Ridge borough', 'Bergen');
INSERT INTO Municipality VALUES ('Parsippany-Troy Hills township', 'Morris');
INSERT INTO Municipality VALUES ('Passaic city', 'Passaic');
INSERT INTO Municipality VALUES ('Paterson city', 'Passaic');
INSERT INTO Municipality VALUES ('Paulsboro borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Peapack and Gladstone borough', 'Somerset');
INSERT INTO Municipality VALUES ('Pemberton borough', 'Burlington');
INSERT INTO Municipality VALUES ('Pemberton township', 'Burlington');
INSERT INTO Municipality VALUES ('Pennington borough', 'Mercer');
INSERT INTO Municipality VALUES ('Penns Grove borough', 'Salem');
INSERT INTO Municipality VALUES ('Pennsauken township', 'Camden');
INSERT INTO Municipality VALUES ('Pennsville township', 'Salem');
INSERT INTO Municipality VALUES ('Pequannock township', 'Morris');
INSERT INTO Municipality VALUES ('Perth Amboy city', 'Middlesex');
INSERT INTO Municipality VALUES ('Phillipsburg town', 'Warren');
INSERT INTO Municipality VALUES ('Pilesgrove township', 'Salem');
INSERT INTO Municipality VALUES ('Pine Beach borough', 'Ocean');
INSERT INTO Municipality VALUES ('Pine Hill borough', 'Camden');
INSERT INTO Municipality VALUES ('Pine Valley borough', 'Camden');
INSERT INTO Municipality VALUES ('Piscataway township', 'Middlesex');
INSERT INTO Municipality VALUES ('Pitman borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Pittsgrove township', 'Salem');
INSERT INTO Municipality VALUES ('Plainfield city', 'Union');
INSERT INTO Municipality VALUES ('Plainsboro township', 'Middlesex');
INSERT INTO Municipality VALUES ('Pleasantville city', 'Atlantic');
INSERT INTO Municipality VALUES ('Plumsted township', 'Ocean');
INSERT INTO Municipality VALUES ('Pohatcong township', 'Warren');
INSERT INTO Municipality VALUES ('Point Pleasant Beach borough', 'Ocean');
INSERT INTO Municipality VALUES ('Point Pleasant borough', 'Ocean');
INSERT INTO Municipality VALUES ('Pompton Lakes borough', 'Passaic');
INSERT INTO Municipality VALUES ('Port Republic city', 'Atlantic');
INSERT INTO Municipality VALUES ('Princeton', 'Mercer');
INSERT INTO Municipality VALUES ('Prospect Park borough', 'Passaic');
INSERT INTO Municipality VALUES ('Quinton township', 'Salem');
INSERT INTO Municipality VALUES ('Rahway city', 'Union');
INSERT INTO Municipality VALUES ('Ramsey borough', 'Bergen');
INSERT INTO Municipality VALUES ('Randolph township', 'Morris');
INSERT INTO Municipality VALUES ('Raritan borough', 'Somerset');
INSERT INTO Municipality VALUES ('Raritan township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Readington township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Red Bank borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Ridgefield borough', 'Bergen');
INSERT INTO Municipality VALUES ('Ridgefield Park village', 'Bergen');
INSERT INTO Municipality VALUES ('Ridgewood village', 'Bergen');
INSERT INTO Municipality VALUES ('Ringwood borough', 'Passaic');
INSERT INTO Municipality VALUES ('River Edge borough', 'Bergen');
INSERT INTO Municipality VALUES ('River Vale township', 'Bergen');
INSERT INTO Municipality VALUES ('Riverdale borough', 'Morris');
INSERT INTO Municipality VALUES ('Riverside township', 'Burlington');
INSERT INTO Municipality VALUES ('Riverton borough', 'Burlington');
INSERT INTO Municipality VALUES ('Robbinsville township', 'Mercer');
INSERT INTO Municipality VALUES ('Rochelle Park township', 'Bergen');
INSERT INTO Municipality VALUES ('Rockaway borough', 'Morris');
INSERT INTO Municipality VALUES ('Rockaway township', 'Morris');
INSERT INTO Municipality VALUES ('Rockleigh borough', 'Bergen');
INSERT INTO Municipality VALUES ('Rocky Hill borough', 'Somerset');
INSERT INTO Municipality VALUES ('Roosevelt borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Roseland borough', 'Essex');
INSERT INTO Municipality VALUES ('Roselle borough', 'Union');
INSERT INTO Municipality VALUES ('Roselle Park borough', 'Union');
INSERT INTO Municipality VALUES ('Roxbury township', 'Morris');
INSERT INTO Municipality VALUES ('Rumson borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Runnemede borough', 'Camden');
INSERT INTO Municipality VALUES ('Rutherford borough', 'Bergen');
INSERT INTO Municipality VALUES ('Saddle Brook township', 'Bergen');
INSERT INTO Municipality VALUES ('Saddle River borough', 'Bergen');
INSERT INTO Municipality VALUES ('Salem city', 'Salem');
INSERT INTO Municipality VALUES ('Sandyston township', 'Sussex');
INSERT INTO Municipality VALUES ('Sayreville borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Scotch Plains township', 'Union');
INSERT INTO Municipality VALUES ('Sea Bright borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Sea Girt borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Sea Isle City city', 'Cape May');
INSERT INTO Municipality VALUES ('Seaside Heights borough', 'Ocean');
INSERT INTO Municipality VALUES ('Seaside Park borough', 'Ocean');
INSERT INTO Municipality VALUES ('Secaucus town', 'Hudson');
INSERT INTO Municipality VALUES ('Shamong township', 'Burlington');
INSERT INTO Municipality VALUES ('Shiloh borough', 'Cumberland');
INSERT INTO Municipality VALUES ('Ship Bottom borough', 'Ocean');
INSERT INTO Municipality VALUES ('Shrewsbury borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Shrewsbury township', 'Monmouth');
INSERT INTO Municipality VALUES ('Somerdale borough', 'Camden');
INSERT INTO Municipality VALUES ('Somers Point city', 'Atlantic');
INSERT INTO Municipality VALUES ('Somerville borough', 'Somerset');
INSERT INTO Municipality VALUES ('South Amboy city', 'Middlesex');
INSERT INTO Municipality VALUES ('South Bound Brook borough', 'Somerset');
INSERT INTO Municipality VALUES ('South Brunswick township', 'Middlesex');
INSERT INTO Municipality VALUES ('South Hackensack township', 'Bergen');
INSERT INTO Municipality VALUES ('South Harrison township', 'Gloucester');
INSERT INTO Municipality VALUES ('South Orange Village township', 'Essex');
INSERT INTO Municipality VALUES ('South Plainfield borough', 'Middlesex');
INSERT INTO Municipality VALUES ('South River borough', 'Middlesex');
INSERT INTO Municipality VALUES ('South Toms River borough', 'Ocean');
INSERT INTO Municipality VALUES ('Southampton township', 'Burlington');
INSERT INTO Municipality VALUES ('Sparta township', 'Sussex');
INSERT INTO Municipality VALUES ('Spotswood borough', 'Middlesex');
INSERT INTO Municipality VALUES ('Spring Lake borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Spring Lake Heights borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Springfield township', 'Burlington');
INSERT INTO Municipality VALUES ('Springfield township', 'Union');
INSERT INTO Municipality VALUES ('Stafford township', 'Ocean');
INSERT INTO Municipality VALUES ('Stanhope borough', 'Sussex');
INSERT INTO Municipality VALUES ('Stillwater township', 'Sussex');
INSERT INTO Municipality VALUES ('Stockton borough', 'Hunterdon');
INSERT INTO Municipality VALUES ('Stone Harbor borough', 'Cape May');
INSERT INTO Municipality VALUES ('Stow Creek township', 'Cumberland');
INSERT INTO Municipality VALUES ('Stratford borough', 'Camden');
INSERT INTO Municipality VALUES ('Summit city', 'Union');
INSERT INTO Municipality VALUES ('Surf City borough', 'Ocean');
INSERT INTO Municipality VALUES ('Sussex borough', 'Sussex');
INSERT INTO Municipality VALUES ('Swedesboro borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Tabernacle township', 'Burlington');
INSERT INTO Municipality VALUES ('Tavistock borough', 'Camden');
INSERT INTO Municipality VALUES ('Teaneck township', 'Bergen');
INSERT INTO Municipality VALUES ('Tenafly borough', 'Bergen');
INSERT INTO Municipality VALUES ('Teterboro borough', 'Bergen');
INSERT INTO Municipality VALUES ('Tewksbury township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Tinton Falls borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Toms River township', 'Ocean');
INSERT INTO Municipality VALUES ('Totowa borough', 'Passaic');
INSERT INTO Municipality VALUES ('Trenton city', 'Mercer');
INSERT INTO Municipality VALUES ('Tuckerton borough', 'Ocean');
INSERT INTO Municipality VALUES ('Union Beach borough', 'Monmouth');
INSERT INTO Municipality VALUES ('Union City city', 'Hudson');
INSERT INTO Municipality VALUES ('Union township', 'Hunterdon');
INSERT INTO Municipality VALUES ('Union township', 'Union');
INSERT INTO Municipality VALUES ('Upper Deerfield township', 'Cumberland');
INSERT INTO Municipality VALUES ('Upper Freehold township', 'Monmouth');
INSERT INTO Municipality VALUES ('Upper Pittsgrove township', 'Salem');
INSERT INTO Municipality VALUES ('Upper Saddle River borough', 'Bergen');
INSERT INTO Municipality VALUES ('Upper township', 'Cape May');
INSERT INTO Municipality VALUES ('Ventnor City city', 'Atlantic');
INSERT INTO Municipality VALUES ('Vernon township', 'Sussex');
INSERT INTO Municipality VALUES ('Verona township', 'Essex');
INSERT INTO Municipality VALUES ('Victory Gardens borough', 'Morris');
INSERT INTO Municipality VALUES ('Vineland city', 'Cumberland');
INSERT INTO Municipality VALUES ('Voorhees township', 'Camden');
INSERT INTO Municipality VALUES ('Waldwick borough', 'Bergen');
INSERT INTO Municipality VALUES ('Wall township', 'Monmouth');
INSERT INTO Municipality VALUES ('Wallington borough', 'Bergen');
INSERT INTO Municipality VALUES ('Walpack township', 'Sussex');
INSERT INTO Municipality VALUES ('Wanaque borough', 'Passaic');
INSERT INTO Municipality VALUES ('Wantage township', 'Sussex');
INSERT INTO Municipality VALUES ('Warren township', 'Somerset');
INSERT INTO Municipality VALUES ('Washington borough', 'Warren');
INSERT INTO Municipality VALUES ('Washington township', 'Bergen');
INSERT INTO Municipality VALUES ('Washington township', 'Burlington');
INSERT INTO Municipality VALUES ('Washington township', 'Gloucester');
INSERT INTO Municipality VALUES ('Washington township', 'Morris');
INSERT INTO Municipality VALUES ('Washington township', 'Warren');
INSERT INTO Municipality VALUES ('Watchung borough', 'Somerset');
INSERT INTO Municipality VALUES ('Waterford township', 'Camden');
INSERT INTO Municipality VALUES ('Wayne township', 'Passaic');
INSERT INTO Municipality VALUES ('Weehawken township', 'Hudson');
INSERT INTO Municipality VALUES ('Wenonah borough', 'Gloucester');
INSERT INTO Municipality VALUES ('West Amwell township', 'Hunterdon');
INSERT INTO Municipality VALUES ('West Caldwell township', 'Essex');
INSERT INTO Municipality VALUES ('West Cape May borough', 'Cape May');
INSERT INTO Municipality VALUES ('West Deptford township', 'Gloucester');
INSERT INTO Municipality VALUES ('West Long Branch borough', 'Monmouth');
INSERT INTO Municipality VALUES ('West Milford township', 'Passaic');
INSERT INTO Municipality VALUES ('West New York town', 'Hudson');
INSERT INTO Municipality VALUES ('West Orange township', 'Essex');
INSERT INTO Municipality VALUES ('West Wildwood borough', 'Cape May');
INSERT INTO Municipality VALUES ('West Windsor township', 'Mercer');
INSERT INTO Municipality VALUES ('Westampton township', 'Burlington');
INSERT INTO Municipality VALUES ('Westfield town', 'Union');
INSERT INTO Municipality VALUES ('Westville borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Westwood borough', 'Bergen');
INSERT INTO Municipality VALUES ('Weymouth township', 'Atlantic');
INSERT INTO Municipality VALUES ('Wharton borough', 'Morris');
INSERT INTO Municipality VALUES ('White township', 'Warren');
INSERT INTO Municipality VALUES ('Wildwood city', 'Cape May');
INSERT INTO Municipality VALUES ('Wildwood Crest borough', 'Cape May');
INSERT INTO Municipality VALUES ('Willingboro township', 'Burlington');
INSERT INTO Municipality VALUES ('Winfield township', 'Union');
INSERT INTO Municipality VALUES ('Winslow township', 'Camden');
INSERT INTO Municipality VALUES ('Woodbine borough', 'Cape May');
INSERT INTO Municipality VALUES ('Woodbridge township', 'Middlesex');
INSERT INTO Municipality VALUES ('Woodbury city', 'Gloucester');
INSERT INTO Municipality VALUES ('Woodbury Heights borough', 'Gloucester');
INSERT INTO Municipality VALUES ('Woodcliff Lake borough', 'Bergen');
INSERT INTO Municipality VALUES ('Woodland Park borough', 'Passaic');
INSERT INTO Municipality VALUES ('Woodland township', 'Burlington');
INSERT INTO Municipality VALUES ('Woodlynne borough', 'Camden');
INSERT INTO Municipality VALUES ('Wood-Ridge borough', 'Bergen');
INSERT INTO Municipality VALUES ('Woodstown borough', 'Salem');
INSERT INTO Municipality VALUES ('Woolwich township', 'Gloucester');
INSERT INTO Municipality VALUES ('Wrightstown borough', 'Burlington');
INSERT INTO Municipality VALUES ('Wyckoff township', 'Bergen');
